// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

///Distributed Clock configuration
type DcConfigInfoResponseT struct {
	SyncMode SyncMode `json:"syncMode"`
	CycleTime uint32 `json:"cycleTime"`
	SyncShiftTime uint32 `json:"syncShiftTime"`
	SyncWindowMonitoring bool `json:"syncWindowMonitoring"`
	DeviationLimit uint32 `json:"deviationLimit"`
	ContinuousDelayCompensation bool `json:"continuousDelayCompensation"`
	SendOffset uint32 `json:"sendOffset"`
	SyncOffset uint32 `json:"syncOffset"`
	OutputShiftTime uint32 `json:"outputShiftTime"`
	InputShiftTime int32 `json:"inputShiftTime"`
}

func (t *DcConfigInfoResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	DcConfigInfoResponseStart(builder)
	DcConfigInfoResponseAddSyncMode(builder, t.SyncMode)
	DcConfigInfoResponseAddCycleTime(builder, t.CycleTime)
	DcConfigInfoResponseAddSyncShiftTime(builder, t.SyncShiftTime)
	DcConfigInfoResponseAddSyncWindowMonitoring(builder, t.SyncWindowMonitoring)
	DcConfigInfoResponseAddDeviationLimit(builder, t.DeviationLimit)
	DcConfigInfoResponseAddContinuousDelayCompensation(builder, t.ContinuousDelayCompensation)
	DcConfigInfoResponseAddSendOffset(builder, t.SendOffset)
	DcConfigInfoResponseAddSyncOffset(builder, t.SyncOffset)
	DcConfigInfoResponseAddOutputShiftTime(builder, t.OutputShiftTime)
	DcConfigInfoResponseAddInputShiftTime(builder, t.InputShiftTime)
	return DcConfigInfoResponseEnd(builder)
}

func (rcv *DcConfigInfoResponse) UnPackTo(t *DcConfigInfoResponseT) {
	t.SyncMode = rcv.SyncMode()
	t.CycleTime = rcv.CycleTime()
	t.SyncShiftTime = rcv.SyncShiftTime()
	t.SyncWindowMonitoring = rcv.SyncWindowMonitoring()
	t.DeviationLimit = rcv.DeviationLimit()
	t.ContinuousDelayCompensation = rcv.ContinuousDelayCompensation()
	t.SendOffset = rcv.SendOffset()
	t.SyncOffset = rcv.SyncOffset()
	t.OutputShiftTime = rcv.OutputShiftTime()
	t.InputShiftTime = rcv.InputShiftTime()
}

func (rcv *DcConfigInfoResponse) UnPack() *DcConfigInfoResponseT {
	if rcv == nil { return nil }
	t := &DcConfigInfoResponseT{}
	rcv.UnPackTo(t)
	return t
}

type DcConfigInfoResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsDcConfigInfoResponse(buf []byte, offset flatbuffers.UOffsetT) *DcConfigInfoResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DcConfigInfoResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDcConfigInfoResponse(buf []byte, offset flatbuffers.UOffsetT) *DcConfigInfoResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DcConfigInfoResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DcConfigInfoResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DcConfigInfoResponse) Table() flatbuffers.Table {
	return rcv._tab
}

///Sync mode of Distributed Clock (DC)
///freerun: slaves are not synchronized
///dcmAuto: DC configuration automatic
///dcmEnabled: DC enabled
///dcmBusShift: DC bus shift
///dcmMasterShift: DC master shift
///dcmLinkLayerRefClock: DC link layer reference clock
///unknown: Sync mode unknown
func (rcv *DcConfigInfoResponse) SyncMode() SyncMode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return SyncMode(rcv._tab.GetUint32(o + rcv._tab.Pos))
	}
	return 0
}

///Sync mode of Distributed Clock (DC)
///freerun: slaves are not synchronized
///dcmAuto: DC configuration automatic
///dcmEnabled: DC enabled
///dcmBusShift: DC bus shift
///dcmMasterShift: DC master shift
///dcmLinkLayerRefClock: DC link layer reference clock
///unknown: Sync mode unknown
func (rcv *DcConfigInfoResponse) MutateSyncMode(n SyncMode) bool {
	return rcv._tab.MutateUint32Slot(4, uint32(n))
}

///Cycle time in microseconds
func (rcv *DcConfigInfoResponse) CycleTime() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

///Cycle time in microseconds
func (rcv *DcConfigInfoResponse) MutateCycleTime(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

///Sync offset in nanoseconds
func (rcv *DcConfigInfoResponse) SyncShiftTime() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

///Sync offset in nanoseconds
func (rcv *DcConfigInfoResponse) MutateSyncShiftTime(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

///Sync windows monitoring
func (rcv *DcConfigInfoResponse) SyncWindowMonitoring() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

///Sync windows monitoring
func (rcv *DcConfigInfoResponse) MutateSyncWindowMonitoring(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

///DC sync window in nanoseconds
func (rcv *DcConfigInfoResponse) DeviationLimit() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

///DC sync window in nanoseconds
func (rcv *DcConfigInfoResponse) MutateDeviationLimit(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

///Continuous delay compensation
func (rcv *DcConfigInfoResponse) ContinuousDelayCompensation() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

///Continuous delay compensation
func (rcv *DcConfigInfoResponse) MutateContinuousDelayCompensation(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

///Send offset in nanoseconds
func (rcv *DcConfigInfoResponse) SendOffset() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

///Send offset in nanoseconds
func (rcv *DcConfigInfoResponse) MutateSendOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

///Sync offset in nanoseconds
func (rcv *DcConfigInfoResponse) SyncOffset() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

///Sync offset in nanoseconds
func (rcv *DcConfigInfoResponse) MutateSyncOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(18, n)
}

///Output shift time in nanoseconds
func (rcv *DcConfigInfoResponse) OutputShiftTime() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

///Output shift time in nanoseconds
func (rcv *DcConfigInfoResponse) MutateOutputShiftTime(n uint32) bool {
	return rcv._tab.MutateUint32Slot(20, n)
}

///Input shift time in nanoseconds
func (rcv *DcConfigInfoResponse) InputShiftTime() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

///Input shift time in nanoseconds
func (rcv *DcConfigInfoResponse) MutateInputShiftTime(n int32) bool {
	return rcv._tab.MutateInt32Slot(22, n)
}

func DcConfigInfoResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func DcConfigInfoResponseAddSyncMode(builder *flatbuffers.Builder, syncMode SyncMode) {
	builder.PrependUint32Slot(0, uint32(syncMode), 0)
}
func DcConfigInfoResponseAddCycleTime(builder *flatbuffers.Builder, cycleTime uint32) {
	builder.PrependUint32Slot(1, cycleTime, 0)
}
func DcConfigInfoResponseAddSyncShiftTime(builder *flatbuffers.Builder, syncShiftTime uint32) {
	builder.PrependUint32Slot(2, syncShiftTime, 0)
}
func DcConfigInfoResponseAddSyncWindowMonitoring(builder *flatbuffers.Builder, syncWindowMonitoring bool) {
	builder.PrependBoolSlot(3, syncWindowMonitoring, false)
}
func DcConfigInfoResponseAddDeviationLimit(builder *flatbuffers.Builder, deviationLimit uint32) {
	builder.PrependUint32Slot(4, deviationLimit, 0)
}
func DcConfigInfoResponseAddContinuousDelayCompensation(builder *flatbuffers.Builder, continuousDelayCompensation bool) {
	builder.PrependBoolSlot(5, continuousDelayCompensation, false)
}
func DcConfigInfoResponseAddSendOffset(builder *flatbuffers.Builder, sendOffset uint32) {
	builder.PrependUint32Slot(6, sendOffset, 0)
}
func DcConfigInfoResponseAddSyncOffset(builder *flatbuffers.Builder, syncOffset uint32) {
	builder.PrependUint32Slot(7, syncOffset, 0)
}
func DcConfigInfoResponseAddOutputShiftTime(builder *flatbuffers.Builder, outputShiftTime uint32) {
	builder.PrependUint32Slot(8, outputShiftTime, 0)
}
func DcConfigInfoResponseAddInputShiftTime(builder *flatbuffers.Builder, inputShiftTime int32) {
	builder.PrependInt32Slot(9, inputShiftTime, 0)
}
func DcConfigInfoResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
