// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EoeConfigInfoT struct {
	Request *AddressedRequestT
	Response *EoeConfigInfoResponseT
}

func (t *EoeConfigInfoT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	requestOffset := t.Request.Pack(builder)
	responseOffset := t.Response.Pack(builder)
	EoeConfigInfoStart(builder)
	EoeConfigInfoAddRequest(builder, requestOffset)
	EoeConfigInfoAddResponse(builder, responseOffset)
	return EoeConfigInfoEnd(builder)
}

func (rcv *EoeConfigInfo) UnPackTo(t *EoeConfigInfoT) {
	t.Request = rcv.Request(nil).UnPack()
	t.Response = rcv.Response(nil).UnPack()
}

func (rcv *EoeConfigInfo) UnPack() *EoeConfigInfoT {
	if rcv == nil { return nil }
	t := &EoeConfigInfoT{}
	rcv.UnPackTo(t)
	return t
}

type EoeConfigInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsEoeConfigInfo(buf []byte, offset flatbuffers.UOffsetT) *EoeConfigInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EoeConfigInfo{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsEoeConfigInfo(buf []byte, offset flatbuffers.UOffsetT) *EoeConfigInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EoeConfigInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *EoeConfigInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EoeConfigInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EoeConfigInfo) Request(obj *AddressedRequest) *AddressedRequest {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(AddressedRequest)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *EoeConfigInfo) Response(obj *EoeConfigInfoResponse) *EoeConfigInfoResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(EoeConfigInfoResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func EoeConfigInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func EoeConfigInfoAddRequest(builder *flatbuffers.Builder, request flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(request), 0)
}
func EoeConfigInfoAddResponse(builder *flatbuffers.Builder, response flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(response), 0)
}
func EoeConfigInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
