// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FoeResponseT struct {
	Data []byte
}

func (t *FoeResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	dataOffset := flatbuffers.UOffsetT(0)
	if t.Data != nil {
		dataOffset = builder.CreateByteString(t.Data)
	}
	FoeResponseStart(builder)
	FoeResponseAddData(builder, dataOffset)
	return FoeResponseEnd(builder)
}

func (rcv *FoeResponse) UnPackTo(t *FoeResponseT) {
	t.Data = rcv.DataBytes()
}

func (rcv *FoeResponse) UnPack() *FoeResponseT {
	if rcv == nil { return nil }
	t := &FoeResponseT{}
	rcv.UnPackTo(t)
	return t
}

type FoeResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsFoeResponse(buf []byte, offset flatbuffers.UOffsetT) *FoeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FoeResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFoeResponse(buf []byte, offset flatbuffers.UOffsetT) *FoeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FoeResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FoeResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FoeResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FoeResponse) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FoeResponse) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FoeResponse) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FoeResponse) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func FoeResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FoeResponseAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func FoeResponseStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func FoeResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
