// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MasterStatusT struct {
	Response *MasterStatusResponseT
}

func (t *MasterStatusT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	responseOffset := t.Response.Pack(builder)
	MasterStatusStart(builder)
	MasterStatusAddResponse(builder, responseOffset)
	return MasterStatusEnd(builder)
}

func (rcv *MasterStatus) UnPackTo(t *MasterStatusT) {
	t.Response = rcv.Response(nil).UnPack()
}

func (rcv *MasterStatus) UnPack() *MasterStatusT {
	if rcv == nil { return nil }
	t := &MasterStatusT{}
	rcv.UnPackTo(t)
	return t
}

type MasterStatus struct {
	_tab flatbuffers.Table
}

func GetRootAsMasterStatus(buf []byte, offset flatbuffers.UOffsetT) *MasterStatus {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MasterStatus{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMasterStatus(buf []byte, offset flatbuffers.UOffsetT) *MasterStatus {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MasterStatus{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *MasterStatus) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MasterStatus) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MasterStatus) Response(obj *MasterStatusResponse) *MasterStatusResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MasterStatusResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MasterStatusStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MasterStatusAddResponse(builder *flatbuffers.Builder, response flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(response), 0)
}
func MasterStatusEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
