// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SDOResponseT struct {
	Data []byte `json:"data"`
}

func (t *SDOResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	dataOffset := flatbuffers.UOffsetT(0)
	if t.Data != nil {
		dataOffset = builder.CreateByteString(t.Data)
	}
	SDOResponseStart(builder)
	SDOResponseAddData(builder, dataOffset)
	return SDOResponseEnd(builder)
}

func (rcv *SDOResponse) UnPackTo(t *SDOResponseT) {
	t.Data = rcv.DataBytes()
}

func (rcv *SDOResponse) UnPack() *SDOResponseT {
	if rcv == nil { return nil }
	t := &SDOResponseT{}
	rcv.UnPackTo(t)
	return t
}

type SDOResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSDOResponse(buf []byte, offset flatbuffers.UOffsetT) *SDOResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SDOResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSDOResponse(buf []byte, offset flatbuffers.UOffsetT) *SDOResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SDOResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SDOResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SDOResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SDOResponse) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SDOResponse) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SDOResponse) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SDOResponse) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func SDOResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SDOResponseAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func SDOResponseStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SDOResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
