// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SlaveStatisticModeSingleShotTriggerT struct {
	Request *SlaveStatisticModeSingleShotTriggerRequestT
	Response *SlaveStatisticModeSingleShotTriggerResponseT
}

func (t *SlaveStatisticModeSingleShotTriggerT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	requestOffset := t.Request.Pack(builder)
	responseOffset := t.Response.Pack(builder)
	SlaveStatisticModeSingleShotTriggerStart(builder)
	SlaveStatisticModeSingleShotTriggerAddRequest(builder, requestOffset)
	SlaveStatisticModeSingleShotTriggerAddResponse(builder, responseOffset)
	return SlaveStatisticModeSingleShotTriggerEnd(builder)
}

func (rcv *SlaveStatisticModeSingleShotTrigger) UnPackTo(t *SlaveStatisticModeSingleShotTriggerT) {
	t.Request = rcv.Request(nil).UnPack()
	t.Response = rcv.Response(nil).UnPack()
}

func (rcv *SlaveStatisticModeSingleShotTrigger) UnPack() *SlaveStatisticModeSingleShotTriggerT {
	if rcv == nil { return nil }
	t := &SlaveStatisticModeSingleShotTriggerT{}
	rcv.UnPackTo(t)
	return t
}

type SlaveStatisticModeSingleShotTrigger struct {
	_tab flatbuffers.Table
}

func GetRootAsSlaveStatisticModeSingleShotTrigger(buf []byte, offset flatbuffers.UOffsetT) *SlaveStatisticModeSingleShotTrigger {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SlaveStatisticModeSingleShotTrigger{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSlaveStatisticModeSingleShotTrigger(buf []byte, offset flatbuffers.UOffsetT) *SlaveStatisticModeSingleShotTrigger {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SlaveStatisticModeSingleShotTrigger{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SlaveStatisticModeSingleShotTrigger) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SlaveStatisticModeSingleShotTrigger) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SlaveStatisticModeSingleShotTrigger) Request(obj *SlaveStatisticModeSingleShotTriggerRequest) *SlaveStatisticModeSingleShotTriggerRequest {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SlaveStatisticModeSingleShotTriggerRequest)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SlaveStatisticModeSingleShotTrigger) Response(obj *SlaveStatisticModeSingleShotTriggerResponse) *SlaveStatisticModeSingleShotTriggerResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SlaveStatisticModeSingleShotTriggerResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SlaveStatisticModeSingleShotTriggerStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SlaveStatisticModeSingleShotTriggerAddRequest(builder *flatbuffers.Builder, request flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(request), 0)
}
func SlaveStatisticModeSingleShotTriggerAddResponse(builder *flatbuffers.Builder, response flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(response), 0)
}
func SlaveStatisticModeSingleShotTriggerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
