// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SlaveVariablesConfigInfoT struct {
	Request *SlaveVariablesConfigInfoRequestT `json:"request"`
	Response *SlaveVariablesConfigInfoResponseListT `json:"response"`
}

func (t *SlaveVariablesConfigInfoT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	requestOffset := t.Request.Pack(builder)
	responseOffset := t.Response.Pack(builder)
	SlaveVariablesConfigInfoStart(builder)
	SlaveVariablesConfigInfoAddRequest(builder, requestOffset)
	SlaveVariablesConfigInfoAddResponse(builder, responseOffset)
	return SlaveVariablesConfigInfoEnd(builder)
}

func (rcv *SlaveVariablesConfigInfo) UnPackTo(t *SlaveVariablesConfigInfoT) {
	t.Request = rcv.Request(nil).UnPack()
	t.Response = rcv.Response(nil).UnPack()
}

func (rcv *SlaveVariablesConfigInfo) UnPack() *SlaveVariablesConfigInfoT {
	if rcv == nil { return nil }
	t := &SlaveVariablesConfigInfoT{}
	rcv.UnPackTo(t)
	return t
}

type SlaveVariablesConfigInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsSlaveVariablesConfigInfo(buf []byte, offset flatbuffers.UOffsetT) *SlaveVariablesConfigInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SlaveVariablesConfigInfo{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSlaveVariablesConfigInfo(buf []byte, offset flatbuffers.UOffsetT) *SlaveVariablesConfigInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SlaveVariablesConfigInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SlaveVariablesConfigInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SlaveVariablesConfigInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SlaveVariablesConfigInfo) Request(obj *SlaveVariablesConfigInfoRequest) *SlaveVariablesConfigInfoRequest {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SlaveVariablesConfigInfoRequest)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SlaveVariablesConfigInfo) Response(obj *SlaveVariablesConfigInfoResponseList) *SlaveVariablesConfigInfoResponseList {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SlaveVariablesConfigInfoResponseList)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SlaveVariablesConfigInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SlaveVariablesConfigInfoAddRequest(builder *flatbuffers.Builder, request flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(request), 0)
}
func SlaveVariablesConfigInfoAddResponse(builder *flatbuffers.Builder, response flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(response), 0)
}
func SlaveVariablesConfigInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
