// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type Controls byte

const (
	ControlsNONE  Controls = 0
	ControlsDebug Controls = 1
)

var EnumNamesControls = map[Controls]string{
	ControlsNONE:  "NONE",
	ControlsDebug: "Debug",
}

var EnumValuesControls = map[string]Controls{
	"NONE":  ControlsNONE,
	"Debug": ControlsDebug,
}

func (v Controls) String() string {
	if s, ok := EnumNamesControls[v]; ok {
		return s
	}
	return "Controls(" + strconv.FormatInt(int64(v), 10) + ")"
}
