// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package oblivion

import "strconv"

type RecordType uint32

const (
	RecordTypeStack       RecordType = 0
	RecordTypeThread      RecordType = 1
	RecordTypeThreadAlloc RecordType = 2
)

var EnumNamesRecordType = map[RecordType]string{
	RecordTypeStack:       "Stack",
	RecordTypeThread:      "Thread",
	RecordTypeThreadAlloc: "ThreadAlloc",
}

var EnumValuesRecordType = map[string]RecordType{
	"Stack":       RecordTypeStack,
	"Thread":      RecordTypeThread,
	"ThreadAlloc": RecordTypeThreadAlloc,
}

func (v RecordType) String() string {
	if s, ok := EnumNamesRecordType[v]; ok {
		return s
	}
	return "RecordType(" + strconv.FormatInt(int64(v), 10) + ")"
}
