// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package enumeration

import "strconv"

type UadpNetworkMessageContentMask uint32

const (
	UadpNetworkMessageContentMaskPublisherId          UadpNetworkMessageContentMask = 1
	UadpNetworkMessageContentMaskGroupHeader          UadpNetworkMessageContentMask = 2
	UadpNetworkMessageContentMaskWriterGroupId        UadpNetworkMessageContentMask = 4
	UadpNetworkMessageContentMaskGroupVersion         UadpNetworkMessageContentMask = 8
	UadpNetworkMessageContentMaskNetworkMessageNumber UadpNetworkMessageContentMask = 16
	UadpNetworkMessageContentMaskSequenceNumber       UadpNetworkMessageContentMask = 32
	UadpNetworkMessageContentMaskPayloadHeader        UadpNetworkMessageContentMask = 64
	UadpNetworkMessageContentMaskTimestamp            UadpNetworkMessageContentMask = 128
	UadpNetworkMessageContentMaskPicoSeconds          UadpNetworkMessageContentMask = 256
	UadpNetworkMessageContentMaskDataSetClassId       UadpNetworkMessageContentMask = 512
	UadpNetworkMessageContentMaskPromotedFields       UadpNetworkMessageContentMask = 1024
)

var EnumNamesUadpNetworkMessageContentMask = map[UadpNetworkMessageContentMask]string{
	UadpNetworkMessageContentMaskPublisherId:          "PublisherId",
	UadpNetworkMessageContentMaskGroupHeader:          "GroupHeader",
	UadpNetworkMessageContentMaskWriterGroupId:        "WriterGroupId",
	UadpNetworkMessageContentMaskGroupVersion:         "GroupVersion",
	UadpNetworkMessageContentMaskNetworkMessageNumber: "NetworkMessageNumber",
	UadpNetworkMessageContentMaskSequenceNumber:       "SequenceNumber",
	UadpNetworkMessageContentMaskPayloadHeader:        "PayloadHeader",
	UadpNetworkMessageContentMaskTimestamp:            "Timestamp",
	UadpNetworkMessageContentMaskPicoSeconds:          "PicoSeconds",
	UadpNetworkMessageContentMaskDataSetClassId:       "DataSetClassId",
	UadpNetworkMessageContentMaskPromotedFields:       "PromotedFields",
}

var EnumValuesUadpNetworkMessageContentMask = map[string]UadpNetworkMessageContentMask{
	"PublisherId":          UadpNetworkMessageContentMaskPublisherId,
	"GroupHeader":          UadpNetworkMessageContentMaskGroupHeader,
	"WriterGroupId":        UadpNetworkMessageContentMaskWriterGroupId,
	"GroupVersion":         UadpNetworkMessageContentMaskGroupVersion,
	"NetworkMessageNumber": UadpNetworkMessageContentMaskNetworkMessageNumber,
	"SequenceNumber":       UadpNetworkMessageContentMaskSequenceNumber,
	"PayloadHeader":        UadpNetworkMessageContentMaskPayloadHeader,
	"Timestamp":            UadpNetworkMessageContentMaskTimestamp,
	"PicoSeconds":          UadpNetworkMessageContentMaskPicoSeconds,
	"DataSetClassId":       UadpNetworkMessageContentMaskDataSetClassId,
	"PromotedFields":       UadpNetworkMessageContentMaskPromotedFields,
}

func (v UadpNetworkMessageContentMask) String() string {
	if s, ok := EnumNamesUadpNetworkMessageContentMask[v]; ok {
		return s
	}
	return "UadpNetworkMessageContentMask(" + strconv.FormatInt(int64(v), 10) + ")"
}
