// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbtypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Cmd_AxsStopT struct {
	Base *Cmd_BaseT `json:"base"`
	DoStop bool `json:"doStop"`
	Dec float64 `json:"dec"`
	JrkDec float64 `json:"jrkDec"`
}

func (t *Cmd_AxsStopT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	baseOffset := t.Base.Pack(builder)
	Cmd_AxsStopStart(builder)
	Cmd_AxsStopAddBase(builder, baseOffset)
	Cmd_AxsStopAddDoStop(builder, t.DoStop)
	Cmd_AxsStopAddDec(builder, t.Dec)
	Cmd_AxsStopAddJrkDec(builder, t.JrkDec)
	return Cmd_AxsStopEnd(builder)
}

func (rcv *Cmd_AxsStop) UnPackTo(t *Cmd_AxsStopT) {
	t.Base = rcv.Base(nil).UnPack()
	t.DoStop = rcv.DoStop()
	t.Dec = rcv.Dec()
	t.JrkDec = rcv.JrkDec()
}

func (rcv *Cmd_AxsStop) UnPack() *Cmd_AxsStopT {
	if rcv == nil { return nil }
	t := &Cmd_AxsStopT{}
	rcv.UnPackTo(t)
	return t
}

type Cmd_AxsStop struct {
	_tab flatbuffers.Table
}

func GetRootAsCmd_AxsStop(buf []byte, offset flatbuffers.UOffsetT) *Cmd_AxsStop {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Cmd_AxsStop{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCmd_AxsStop(buf []byte, offset flatbuffers.UOffsetT) *Cmd_AxsStop {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Cmd_AxsStop{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Cmd_AxsStop) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Cmd_AxsStop) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Cmd_AxsStop) Base(obj *Cmd_Base) *Cmd_Base {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Cmd_Base)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Cmd_AxsStop) DoStop() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Cmd_AxsStop) MutateDoStop(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *Cmd_AxsStop) Dec() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Cmd_AxsStop) MutateDec(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func (rcv *Cmd_AxsStop) JrkDec() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Cmd_AxsStop) MutateJrkDec(n float64) bool {
	return rcv._tab.MutateFloat64Slot(10, n)
}

func Cmd_AxsStopStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func Cmd_AxsStopAddBase(builder *flatbuffers.Builder, base flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(base), 0)
}
func Cmd_AxsStopAddDoStop(builder *flatbuffers.Builder, doStop bool) {
	builder.PrependBoolSlot(1, doStop, false)
}
func Cmd_AxsStopAddDec(builder *flatbuffers.Builder, dec float64) {
	builder.PrependFloat64Slot(2, dec, 0.0)
}
func Cmd_AxsStopAddJrkDec(builder *flatbuffers.Builder, jrkDec float64) {
	builder.PrependFloat64Slot(3, jrkDec, 0.0)
}
func Cmd_AxsStopEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
