// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbtypes

import "strconv"

type CmdType_ListRegisteredCmdsOptions int8

const (
	CmdType_ListRegisteredCmdsOptionsUNKNOWN    CmdType_ListRegisteredCmdsOptions = 0
	CmdType_ListRegisteredCmdsOptionsCMD        CmdType_ListRegisteredCmdsOptions = 1
	CmdType_ListRegisteredCmdsOptionsCMD_OPTION CmdType_ListRegisteredCmdsOptions = 2
)

var EnumNamesCmdType_ListRegisteredCmdsOptions = map[CmdType_ListRegisteredCmdsOptions]string{
	CmdType_ListRegisteredCmdsOptionsUNKNOWN:    "UNKNOWN",
	CmdType_ListRegisteredCmdsOptionsCMD:        "CMD",
	CmdType_ListRegisteredCmdsOptionsCMD_OPTION: "CMD_OPTION",
}

var EnumValuesCmdType_ListRegisteredCmdsOptions = map[string]CmdType_ListRegisteredCmdsOptions{
	"UNKNOWN":    CmdType_ListRegisteredCmdsOptionsUNKNOWN,
	"CMD":        CmdType_ListRegisteredCmdsOptionsCMD,
	"CMD_OPTION": CmdType_ListRegisteredCmdsOptionsCMD_OPTION,
}

func (v CmdType_ListRegisteredCmdsOptions) String() string {
	if s, ok := EnumNamesCmdType_ListRegisteredCmdsOptions[v]; ok {
		return s
	}
	return "CmdType_ListRegisteredCmdsOptions(" + strconv.FormatInt(int64(v), 10) + ")"
}
