// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbtypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Parameters of the runCalculationPipeline function
type Misc_RunCalculationPipelineDataT struct {
	AxsName string
	PipelineName string
	CmdMode SyncCmdMode
	MasterName string
	Inputs []float64
}

func (t *Misc_RunCalculationPipelineDataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	axsNameOffset := builder.CreateString(t.AxsName)
	pipelineNameOffset := builder.CreateString(t.PipelineName)
	masterNameOffset := builder.CreateString(t.MasterName)
	inputsOffset := flatbuffers.UOffsetT(0)
	if t.Inputs != nil {
		inputsLength := len(t.Inputs)
		Misc_RunCalculationPipelineDataStartInputsVector(builder, inputsLength)
		for j := inputsLength - 1; j >= 0; j-- {
			builder.PrependFloat64(t.Inputs[j])
		}
		inputsOffset = builder.EndVector(inputsLength)
	}
	Misc_RunCalculationPipelineDataStart(builder)
	Misc_RunCalculationPipelineDataAddAxsName(builder, axsNameOffset)
	Misc_RunCalculationPipelineDataAddPipelineName(builder, pipelineNameOffset)
	Misc_RunCalculationPipelineDataAddCmdMode(builder, t.CmdMode)
	Misc_RunCalculationPipelineDataAddMasterName(builder, masterNameOffset)
	Misc_RunCalculationPipelineDataAddInputs(builder, inputsOffset)
	return Misc_RunCalculationPipelineDataEnd(builder)
}

func (rcv *Misc_RunCalculationPipelineData) UnPackTo(t *Misc_RunCalculationPipelineDataT) {
	t.AxsName = string(rcv.AxsName())
	t.PipelineName = string(rcv.PipelineName())
	t.CmdMode = rcv.CmdMode()
	t.MasterName = string(rcv.MasterName())
	inputsLength := rcv.InputsLength()
	t.Inputs = make([]float64, inputsLength)
	for j := 0; j < inputsLength; j++ {
		t.Inputs[j] = rcv.Inputs(j)
	}
}

func (rcv *Misc_RunCalculationPipelineData) UnPack() *Misc_RunCalculationPipelineDataT {
	if rcv == nil { return nil }
	t := &Misc_RunCalculationPipelineDataT{}
	rcv.UnPackTo(t)
	return t
}

type Misc_RunCalculationPipelineData struct {
	_tab flatbuffers.Table
}

func GetRootAsMisc_RunCalculationPipelineData(buf []byte, offset flatbuffers.UOffsetT) *Misc_RunCalculationPipelineData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Misc_RunCalculationPipelineData{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMisc_RunCalculationPipelineData(buf []byte, offset flatbuffers.UOffsetT) *Misc_RunCalculationPipelineData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Misc_RunCalculationPipelineData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Misc_RunCalculationPipelineData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Misc_RunCalculationPipelineData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Misc_RunCalculationPipelineData) AxsName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Misc_RunCalculationPipelineData) PipelineName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Misc_RunCalculationPipelineData) CmdMode() SyncCmdMode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return SyncCmdMode(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Misc_RunCalculationPipelineData) MutateCmdMode(n SyncCmdMode) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *Misc_RunCalculationPipelineData) MasterName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Misc_RunCalculationPipelineData) Inputs(j int) float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *Misc_RunCalculationPipelineData) InputsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Misc_RunCalculationPipelineData) MutateInputs(j int, n float64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func Misc_RunCalculationPipelineDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func Misc_RunCalculationPipelineDataAddAxsName(builder *flatbuffers.Builder, axsName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(axsName), 0)
}
func Misc_RunCalculationPipelineDataAddPipelineName(builder *flatbuffers.Builder, pipelineName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(pipelineName), 0)
}
func Misc_RunCalculationPipelineDataAddCmdMode(builder *flatbuffers.Builder, cmdMode SyncCmdMode) {
	builder.PrependInt8Slot(2, int8(cmdMode), 0)
}
func Misc_RunCalculationPipelineDataAddMasterName(builder *flatbuffers.Builder, masterName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(masterName), 0)
}
func Misc_RunCalculationPipelineDataAddInputs(builder *flatbuffers.Builder, inputs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(inputs), 0)
}
func Misc_RunCalculationPipelineDataStartInputsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func Misc_RunCalculationPipelineDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
