// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// This table defines the required element to request the main diagnostic text of a diagnostic log.
type GetMainDiagnosisTextT struct {
	MainDiagnosisNumber string `json:"mainDiagnosisNumber"`
}

func (t *GetMainDiagnosisTextT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	mainDiagnosisNumberOffset := flatbuffers.UOffsetT(0)
	if t.MainDiagnosisNumber != "" {
		mainDiagnosisNumberOffset = builder.CreateString(t.MainDiagnosisNumber)
	}
	GetMainDiagnosisTextStart(builder)
	GetMainDiagnosisTextAddMainDiagnosisNumber(builder, mainDiagnosisNumberOffset)
	return GetMainDiagnosisTextEnd(builder)
}

func (rcv *GetMainDiagnosisText) UnPackTo(t *GetMainDiagnosisTextT) {
	t.MainDiagnosisNumber = string(rcv.MainDiagnosisNumber())
}

func (rcv *GetMainDiagnosisText) UnPack() *GetMainDiagnosisTextT {
	if rcv == nil { return nil }
	t := &GetMainDiagnosisTextT{}
	rcv.UnPackTo(t)
	return t
}

type GetMainDiagnosisText struct {
	_tab flatbuffers.Table
}

func GetRootAsGetMainDiagnosisText(buf []byte, offset flatbuffers.UOffsetT) *GetMainDiagnosisText {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetMainDiagnosisText{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsGetMainDiagnosisText(buf []byte, offset flatbuffers.UOffsetT) *GetMainDiagnosisText {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetMainDiagnosisText{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *GetMainDiagnosisText) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetMainDiagnosisText) Table() flatbuffers.Table {
	return rcv._tab
}

/// Main diagnostic number.
func (rcv *GetMainDiagnosisText) MainDiagnosisNumber() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Main diagnostic number.
func GetMainDiagnosisTextStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetMainDiagnosisTextAddMainDiagnosisNumber(builder *flatbuffers.Builder, mainDiagnosisNumber flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(mainDiagnosisNumber), 0)
}
func GetMainDiagnosisTextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
