// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package builtin

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ArrayOfNodeIdT struct {
	Array []*NodeIdT `json:"array"`
}

func (t *ArrayOfNodeIdT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	arrayOffset := flatbuffers.UOffsetT(0)
	if t.Array != nil {
		arrayLength := len(t.Array)
		arrayOffsets := make([]flatbuffers.UOffsetT, arrayLength)
		for j := 0; j < arrayLength; j++ {
			arrayOffsets[j] = t.Array[j].Pack(builder)
		}
		ArrayOfNodeIdStartArrayVector(builder, arrayLength)
		for j := arrayLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(arrayOffsets[j])
		}
		arrayOffset = builder.EndVector(arrayLength)
	}
	ArrayOfNodeIdStart(builder)
	ArrayOfNodeIdAddArray(builder, arrayOffset)
	return ArrayOfNodeIdEnd(builder)
}

func (rcv *ArrayOfNodeId) UnPackTo(t *ArrayOfNodeIdT) {
	arrayLength := rcv.ArrayLength()
	t.Array = make([]*NodeIdT, arrayLength)
	for j := 0; j < arrayLength; j++ {
		x := NodeId{}
		rcv.Array(&x, j)
		t.Array[j] = x.UnPack()
	}
}

func (rcv *ArrayOfNodeId) UnPack() *ArrayOfNodeIdT {
	if rcv == nil { return nil }
	t := &ArrayOfNodeIdT{}
	rcv.UnPackTo(t)
	return t
}

type ArrayOfNodeId struct {
	_tab flatbuffers.Table
}

func GetRootAsArrayOfNodeId(buf []byte, offset flatbuffers.UOffsetT) *ArrayOfNodeId {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ArrayOfNodeId{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsArrayOfNodeId(buf []byte, offset flatbuffers.UOffsetT) *ArrayOfNodeId {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ArrayOfNodeId{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ArrayOfNodeId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ArrayOfNodeId) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ArrayOfNodeId) Array(obj *NodeId, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ArrayOfNodeId) ArrayLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ArrayOfNodeIdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ArrayOfNodeIdAddArray(builder *flatbuffers.Builder, array flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(array), 0)
}
func ArrayOfNodeIdStartArrayVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ArrayOfNodeIdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
