// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package builtin

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FloatVariantT struct {
	Value float32 `json:"value"`
}

func (t *FloatVariantT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	FloatVariantStart(builder)
	FloatVariantAddValue(builder, t.Value)
	return FloatVariantEnd(builder)
}

func (rcv *FloatVariant) UnPackTo(t *FloatVariantT) {
	t.Value = rcv.Value()
}

func (rcv *FloatVariant) UnPack() *FloatVariantT {
	if rcv == nil { return nil }
	t := &FloatVariantT{}
	rcv.UnPackTo(t)
	return t
}

type FloatVariant struct {
	_tab flatbuffers.Table
}

func GetRootAsFloatVariant(buf []byte, offset flatbuffers.UOffsetT) *FloatVariant {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FloatVariant{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFloatVariant(buf []byte, offset flatbuffers.UOffsetT) *FloatVariant {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FloatVariant{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FloatVariant) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FloatVariant) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FloatVariant) Value() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FloatVariant) MutateValue(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func FloatVariantStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FloatVariantAddValue(builder *flatbuffers.Builder, value float32) {
	builder.PrependFloat32Slot(0, value, 0.0)
}
func FloatVariantEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
