// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StationNameRequestT struct {
	Name string `json:"name"`
}

func (t *StationNameRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	nameOffset := flatbuffers.UOffsetT(0)
	if t.Name != "" {
		nameOffset = builder.CreateString(t.Name)
	}
	StationNameRequestStart(builder)
	StationNameRequestAddName(builder, nameOffset)
	return StationNameRequestEnd(builder)
}

func (rcv *StationNameRequest) UnPackTo(t *StationNameRequestT) {
	t.Name = string(rcv.Name())
}

func (rcv *StationNameRequest) UnPack() *StationNameRequestT {
	if rcv == nil { return nil }
	t := &StationNameRequestT{}
	rcv.UnPackTo(t)
	return t
}

type StationNameRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsStationNameRequest(buf []byte, offset flatbuffers.UOffsetT) *StationNameRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StationNameRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStationNameRequest(buf []byte, offset flatbuffers.UOffsetT) *StationNameRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StationNameRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *StationNameRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StationNameRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StationNameRequest) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StationNameRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StationNameRequestAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func StationNameRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
