// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package remote

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConfigItem struct {
	_tab flatbuffers.Table
}

func GetRootAsConfigItem(buf []byte, offset flatbuffers.UOffsetT) *ConfigItem {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConfigItem{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsConfigItem(buf []byte, offset flatbuffers.UOffsetT) *ConfigItem {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConfigItem{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ConfigItem) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConfigItem) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConfigItem) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConfigItem) Address() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConfigItemStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ConfigItemAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func ConfigItemAddAddress(builder *flatbuffers.Builder, address flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(address), 0)
}
func ConfigItemEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
