// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbtypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// configuration for coupling functions for a single axis
type AxsCfgCoupling struct {
	_tab flatbuffers.Table
}

func GetRootAsAxsCfgCoupling(buf []byte, offset flatbuffers.UOffsetT) *AxsCfgCoupling {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AxsCfgCoupling{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAxsCfgCoupling(buf []byte, offset flatbuffers.UOffsetT) *AxsCfgCoupling {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AxsCfgCoupling{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AxsCfgCoupling) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AxsCfgCoupling) Table() flatbuffers.Table {
	return rcv._tab
}

/// configuration for gantry coupling function of a single axis
func (rcv *AxsCfgCoupling) Gantry(obj *AxsCfgGantry) *AxsCfgGantry {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(AxsCfgGantry)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// configuration for gantry coupling function of a single axis
func AxsCfgCouplingStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AxsCfgCouplingAddGantry(builder *flatbuffers.Builder, gantry flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(gantry), 0)
}
func AxsCfgCouplingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
