// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbtypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// One pair with value and meaning for the internal kinematics pose (used for commanding)
type KinCmdPosePairT struct {
	Value float64 `json:"value"`
	ExtMeaning *ExtMeaningT `json:"extMeaning"`
}

func (t *KinCmdPosePairT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	extMeaningOffset := t.ExtMeaning.Pack(builder)
	KinCmdPosePairStart(builder)
	KinCmdPosePairAddValue(builder, t.Value)
	KinCmdPosePairAddExtMeaning(builder, extMeaningOffset)
	return KinCmdPosePairEnd(builder)
}

func (rcv *KinCmdPosePair) UnPackTo(t *KinCmdPosePairT) {
	t.Value = rcv.Value()
	t.ExtMeaning = rcv.ExtMeaning(nil).UnPack()
}

func (rcv *KinCmdPosePair) UnPack() *KinCmdPosePairT {
	if rcv == nil { return nil }
	t := &KinCmdPosePairT{}
	rcv.UnPackTo(t)
	return t
}

type KinCmdPosePair struct {
	_tab flatbuffers.Table
}

func GetRootAsKinCmdPosePair(buf []byte, offset flatbuffers.UOffsetT) *KinCmdPosePair {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KinCmdPosePair{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsKinCmdPosePair(buf []byte, offset flatbuffers.UOffsetT) *KinCmdPosePair {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KinCmdPosePair{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *KinCmdPosePair) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KinCmdPosePair) Table() flatbuffers.Table {
	return rcv._tab
}

/// one value of cmdKinPos
func (rcv *KinCmdPosePair) Value() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

/// one value of cmdKinPos
func (rcv *KinCmdPosePair) MutateValue(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

/// extended meaning { meaning, attribute }
func (rcv *KinCmdPosePair) ExtMeaning(obj *ExtMeaning) *ExtMeaning {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ExtMeaning)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// extended meaning { meaning, attribute }
func KinCmdPosePairStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func KinCmdPosePairAddValue(builder *flatbuffers.Builder, value float64) {
	builder.PrependFloat64Slot(0, value, 0.0)
}
func KinCmdPosePairAddExtMeaning(builder *flatbuffers.Builder, extMeaning flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(extMeaning), 0)
}
func KinCmdPosePairEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
