// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbtypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// parameters for the move 3D circular commands for a kinematics
type KinCmd3dCircleDataT struct {
	CmdKinPose []*KinCmdPosePairT `json:"cmdKinPose"`
	CmdCircleData []*KinCmd3dCircleDataPairT `json:"cmdCircleData"`
	CoordSys CoordSys `json:"coordSys"`
	Lim *DynamicLimitsT `json:"lim"`
}

func (t *KinCmd3dCircleDataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	cmdKinPoseOffset := flatbuffers.UOffsetT(0)
	if t.CmdKinPose != nil {
		cmdKinPoseLength := len(t.CmdKinPose)
		cmdKinPoseOffsets := make([]flatbuffers.UOffsetT, cmdKinPoseLength)
		for j := 0; j < cmdKinPoseLength; j++ {
			cmdKinPoseOffsets[j] = t.CmdKinPose[j].Pack(builder)
		}
		KinCmd3dCircleDataStartCmdKinPoseVector(builder, cmdKinPoseLength)
		for j := cmdKinPoseLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(cmdKinPoseOffsets[j])
		}
		cmdKinPoseOffset = builder.EndVector(cmdKinPoseLength)
	}
	cmdCircleDataOffset := flatbuffers.UOffsetT(0)
	if t.CmdCircleData != nil {
		cmdCircleDataLength := len(t.CmdCircleData)
		cmdCircleDataOffsets := make([]flatbuffers.UOffsetT, cmdCircleDataLength)
		for j := 0; j < cmdCircleDataLength; j++ {
			cmdCircleDataOffsets[j] = t.CmdCircleData[j].Pack(builder)
		}
		KinCmd3dCircleDataStartCmdCircleDataVector(builder, cmdCircleDataLength)
		for j := cmdCircleDataLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(cmdCircleDataOffsets[j])
		}
		cmdCircleDataOffset = builder.EndVector(cmdCircleDataLength)
	}
	limOffset := t.Lim.Pack(builder)
	KinCmd3dCircleDataStart(builder)
	KinCmd3dCircleDataAddCmdKinPose(builder, cmdKinPoseOffset)
	KinCmd3dCircleDataAddCmdCircleData(builder, cmdCircleDataOffset)
	KinCmd3dCircleDataAddCoordSys(builder, t.CoordSys)
	KinCmd3dCircleDataAddLim(builder, limOffset)
	return KinCmd3dCircleDataEnd(builder)
}

func (rcv *KinCmd3dCircleData) UnPackTo(t *KinCmd3dCircleDataT) {
	cmdKinPoseLength := rcv.CmdKinPoseLength()
	t.CmdKinPose = make([]*KinCmdPosePairT, cmdKinPoseLength)
	for j := 0; j < cmdKinPoseLength; j++ {
		x := KinCmdPosePair{}
		rcv.CmdKinPose(&x, j)
		t.CmdKinPose[j] = x.UnPack()
	}
	cmdCircleDataLength := rcv.CmdCircleDataLength()
	t.CmdCircleData = make([]*KinCmd3dCircleDataPairT, cmdCircleDataLength)
	for j := 0; j < cmdCircleDataLength; j++ {
		x := KinCmd3dCircleDataPair{}
		rcv.CmdCircleData(&x, j)
		t.CmdCircleData[j] = x.UnPack()
	}
	t.CoordSys = rcv.CoordSys()
	t.Lim = rcv.Lim(nil).UnPack()
}

func (rcv *KinCmd3dCircleData) UnPack() *KinCmd3dCircleDataT {
	if rcv == nil { return nil }
	t := &KinCmd3dCircleDataT{}
	rcv.UnPackTo(t)
	return t
}

type KinCmd3dCircleData struct {
	_tab flatbuffers.Table
}

func GetRootAsKinCmd3dCircleData(buf []byte, offset flatbuffers.UOffsetT) *KinCmd3dCircleData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KinCmd3dCircleData{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsKinCmd3dCircleData(buf []byte, offset flatbuffers.UOffsetT) *KinCmd3dCircleData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KinCmd3dCircleData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *KinCmd3dCircleData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KinCmd3dCircleData) Table() flatbuffers.Table {
	return rcv._tab
}

/// commanded target position with meanings
func (rcv *KinCmd3dCircleData) CmdKinPose(obj *KinCmdPosePair, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *KinCmd3dCircleData) CmdKinPoseLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// commanded target position with meanings
/// commanded circle data with 3d circle meanings
func (rcv *KinCmd3dCircleData) CmdCircleData(obj *KinCmd3dCircleDataPair, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *KinCmd3dCircleData) CmdCircleDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// commanded circle data with 3d circle meanings
/// coordSys for commanded target position
func (rcv *KinCmd3dCircleData) CoordSys() CoordSys {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return CoordSys(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// coordSys for commanded target position
func (rcv *KinCmd3dCircleData) MutateCoordSys(n CoordSys) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

/// dynamic limits for the motion of this command
func (rcv *KinCmd3dCircleData) Lim(obj *DynamicLimits) *DynamicLimits {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DynamicLimits)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// dynamic limits for the motion of this command
func KinCmd3dCircleDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func KinCmd3dCircleDataAddCmdKinPose(builder *flatbuffers.Builder, cmdKinPose flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(cmdKinPose), 0)
}
func KinCmd3dCircleDataStartCmdKinPoseVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func KinCmd3dCircleDataAddCmdCircleData(builder *flatbuffers.Builder, cmdCircleData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(cmdCircleData), 0)
}
func KinCmd3dCircleDataStartCmdCircleDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func KinCmd3dCircleDataAddCoordSys(builder *flatbuffers.Builder, coordSys CoordSys) {
	builder.PrependInt8Slot(2, int8(coordSys), 0)
}
func KinCmd3dCircleDataAddLim(builder *flatbuffers.Builder, lim flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(lim), 0)
}
func KinCmd3dCircleDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
