// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbtypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Table for a vector of double+unit values
type KVPCfgDoubleUnitVectorT struct {
	DoubleVector []*KVPCfgDoubleUnitT `json:"doubleVector"`
}

func (t *KVPCfgDoubleUnitVectorT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	doubleVectorOffset := flatbuffers.UOffsetT(0)
	if t.DoubleVector != nil {
		doubleVectorLength := len(t.DoubleVector)
		doubleVectorOffsets := make([]flatbuffers.UOffsetT, doubleVectorLength)
		for j := 0; j < doubleVectorLength; j++ {
			doubleVectorOffsets[j] = t.DoubleVector[j].Pack(builder)
		}
		KVPCfgDoubleUnitVectorStartDoubleVectorVector(builder, doubleVectorLength)
		for j := doubleVectorLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(doubleVectorOffsets[j])
		}
		doubleVectorOffset = builder.EndVector(doubleVectorLength)
	}
	KVPCfgDoubleUnitVectorStart(builder)
	KVPCfgDoubleUnitVectorAddDoubleVector(builder, doubleVectorOffset)
	return KVPCfgDoubleUnitVectorEnd(builder)
}

func (rcv *KVPCfgDoubleUnitVector) UnPackTo(t *KVPCfgDoubleUnitVectorT) {
	doubleVectorLength := rcv.DoubleVectorLength()
	t.DoubleVector = make([]*KVPCfgDoubleUnitT, doubleVectorLength)
	for j := 0; j < doubleVectorLength; j++ {
		x := KVPCfgDoubleUnit{}
		rcv.DoubleVector(&x, j)
		t.DoubleVector[j] = x.UnPack()
	}
}

func (rcv *KVPCfgDoubleUnitVector) UnPack() *KVPCfgDoubleUnitVectorT {
	if rcv == nil { return nil }
	t := &KVPCfgDoubleUnitVectorT{}
	rcv.UnPackTo(t)
	return t
}

type KVPCfgDoubleUnitVector struct {
	_tab flatbuffers.Table
}

func GetRootAsKVPCfgDoubleUnitVector(buf []byte, offset flatbuffers.UOffsetT) *KVPCfgDoubleUnitVector {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KVPCfgDoubleUnitVector{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsKVPCfgDoubleUnitVector(buf []byte, offset flatbuffers.UOffsetT) *KVPCfgDoubleUnitVector {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KVPCfgDoubleUnitVector{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *KVPCfgDoubleUnitVector) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KVPCfgDoubleUnitVector) Table() flatbuffers.Table {
	return rcv._tab
}

/// vector of double numbers with units
func (rcv *KVPCfgDoubleUnitVector) DoubleVector(obj *KVPCfgDoubleUnit, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *KVPCfgDoubleUnitVector) DoubleVectorLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// vector of double numbers with units
func KVPCfgDoubleUnitVectorStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func KVPCfgDoubleUnitVectorAddDoubleVector(builder *flatbuffers.Builder, doubleVector flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(doubleVector), 0)
}
func KVPCfgDoubleUnitVectorStartDoubleVectorVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func KVPCfgDoubleUnitVectorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
