// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbtypes

import "strconv"

/// type of the safe areas execution error reaction
type SafeAreasExecErrReaction int8

const (
	/// brake on path with commanded dynamics, if an violation of the safe areas occurred
	SafeAreasExecErrReactionLIGHT_ERROR  SafeAreasExecErrReaction = 0
	/// stop each axis individually with maximum dynamics if an violation of the safe areas occurred
	SafeAreasExecErrReactionSEVERE_ERROR SafeAreasExecErrReaction = 1
)

var EnumNamesSafeAreasExecErrReaction = map[SafeAreasExecErrReaction]string{
	SafeAreasExecErrReactionLIGHT_ERROR:  "LIGHT_ERROR",
	SafeAreasExecErrReactionSEVERE_ERROR: "SEVERE_ERROR",
}

var EnumValuesSafeAreasExecErrReaction = map[string]SafeAreasExecErrReaction{
	"LIGHT_ERROR":  SafeAreasExecErrReactionLIGHT_ERROR,
	"SEVERE_ERROR": SafeAreasExecErrReactionSEVERE_ERROR,
}

func (v SafeAreasExecErrReaction) String() string {
	if s, ok := EnumNamesSafeAreasExecErrReaction[v]; ok {
		return s
	}
	return "SafeAreasExecErrReaction(" + strconv.FormatInt(int64(v), 10) + ")"
}
