// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbtypes

import (
	"bytes"
	flatbuffers "github.com/google/flatbuffers/go"
)

/// configuration of a single set for the tool data
type SysCfgToolDataSetT struct {
	SetName string `json:"setName"`
	OffsetXyz []float64 `json:"offsetXYZ"`
	Orientation []float64 `json:"orientation"`
	ToolRadius float64 `json:"toolRadius"`
	ToolDataEdgeOri ToolDataEdgeOri `json:"toolDataEdgeOri"`
	OffsetXyzunits []string `json:"offsetXYZUnits"`
	OrientationUnits []string `json:"orientationUnits"`
	ToolRadiusUnit string `json:"toolRadiusUnit"`
}

func (t *SysCfgToolDataSetT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	setNameOffset := flatbuffers.UOffsetT(0)
	if t.SetName != "" {
		setNameOffset = builder.CreateString(t.SetName)
	}
	offsetXyzOffset := flatbuffers.UOffsetT(0)
	if t.OffsetXyz != nil {
		offsetXyzLength := len(t.OffsetXyz)
		SysCfgToolDataSetStartOffsetXyzVector(builder, offsetXyzLength)
		for j := offsetXyzLength - 1; j >= 0; j-- {
			builder.PrependFloat64(t.OffsetXyz[j])
		}
		offsetXyzOffset = builder.EndVector(offsetXyzLength)
	}
	orientationOffset := flatbuffers.UOffsetT(0)
	if t.Orientation != nil {
		orientationLength := len(t.Orientation)
		SysCfgToolDataSetStartOrientationVector(builder, orientationLength)
		for j := orientationLength - 1; j >= 0; j-- {
			builder.PrependFloat64(t.Orientation[j])
		}
		orientationOffset = builder.EndVector(orientationLength)
	}
	offsetXyzunitsOffset := flatbuffers.UOffsetT(0)
	if t.OffsetXyzunits != nil {
		offsetXyzunitsLength := len(t.OffsetXyzunits)
		offsetXyzunitsOffsets := make([]flatbuffers.UOffsetT, offsetXyzunitsLength)
		for j := 0; j < offsetXyzunitsLength; j++ {
			offsetXyzunitsOffsets[j] = builder.CreateString(t.OffsetXyzunits[j])
		}
		SysCfgToolDataSetStartOffsetXyzunitsVector(builder, offsetXyzunitsLength)
		for j := offsetXyzunitsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(offsetXyzunitsOffsets[j])
		}
		offsetXyzunitsOffset = builder.EndVector(offsetXyzunitsLength)
	}
	orientationUnitsOffset := flatbuffers.UOffsetT(0)
	if t.OrientationUnits != nil {
		orientationUnitsLength := len(t.OrientationUnits)
		orientationUnitsOffsets := make([]flatbuffers.UOffsetT, orientationUnitsLength)
		for j := 0; j < orientationUnitsLength; j++ {
			orientationUnitsOffsets[j] = builder.CreateString(t.OrientationUnits[j])
		}
		SysCfgToolDataSetStartOrientationUnitsVector(builder, orientationUnitsLength)
		for j := orientationUnitsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(orientationUnitsOffsets[j])
		}
		orientationUnitsOffset = builder.EndVector(orientationUnitsLength)
	}
	toolRadiusUnitOffset := flatbuffers.UOffsetT(0)
	if t.ToolRadiusUnit != "" {
		toolRadiusUnitOffset = builder.CreateString(t.ToolRadiusUnit)
	}
	SysCfgToolDataSetStart(builder)
	SysCfgToolDataSetAddSetName(builder, setNameOffset)
	SysCfgToolDataSetAddOffsetXyz(builder, offsetXyzOffset)
	SysCfgToolDataSetAddOrientation(builder, orientationOffset)
	SysCfgToolDataSetAddToolRadius(builder, t.ToolRadius)
	SysCfgToolDataSetAddToolDataEdgeOri(builder, t.ToolDataEdgeOri)
	SysCfgToolDataSetAddOffsetXyzunits(builder, offsetXyzunitsOffset)
	SysCfgToolDataSetAddOrientationUnits(builder, orientationUnitsOffset)
	SysCfgToolDataSetAddToolRadiusUnit(builder, toolRadiusUnitOffset)
	return SysCfgToolDataSetEnd(builder)
}

func (rcv *SysCfgToolDataSet) UnPackTo(t *SysCfgToolDataSetT) {
	t.SetName = string(rcv.SetName())
	offsetXyzLength := rcv.OffsetXyzLength()
	t.OffsetXyz = make([]float64, offsetXyzLength)
	for j := 0; j < offsetXyzLength; j++ {
		t.OffsetXyz[j] = rcv.OffsetXyz(j)
	}
	orientationLength := rcv.OrientationLength()
	t.Orientation = make([]float64, orientationLength)
	for j := 0; j < orientationLength; j++ {
		t.Orientation[j] = rcv.Orientation(j)
	}
	t.ToolRadius = rcv.ToolRadius()
	t.ToolDataEdgeOri = rcv.ToolDataEdgeOri()
	offsetXyzunitsLength := rcv.OffsetXyzunitsLength()
	t.OffsetXyzunits = make([]string, offsetXyzunitsLength)
	for j := 0; j < offsetXyzunitsLength; j++ {
		t.OffsetXyzunits[j] = string(rcv.OffsetXyzunits(j))
	}
	orientationUnitsLength := rcv.OrientationUnitsLength()
	t.OrientationUnits = make([]string, orientationUnitsLength)
	for j := 0; j < orientationUnitsLength; j++ {
		t.OrientationUnits[j] = string(rcv.OrientationUnits(j))
	}
	t.ToolRadiusUnit = string(rcv.ToolRadiusUnit())
}

func (rcv *SysCfgToolDataSet) UnPack() *SysCfgToolDataSetT {
	if rcv == nil { return nil }
	t := &SysCfgToolDataSetT{}
	rcv.UnPackTo(t)
	return t
}

type SysCfgToolDataSet struct {
	_tab flatbuffers.Table
}

func GetRootAsSysCfgToolDataSet(buf []byte, offset flatbuffers.UOffsetT) *SysCfgToolDataSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SysCfgToolDataSet{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSysCfgToolDataSet(buf []byte, offset flatbuffers.UOffsetT) *SysCfgToolDataSet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SysCfgToolDataSet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SysCfgToolDataSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SysCfgToolDataSet) Table() flatbuffers.Table {
	return rcv._tab
}

/// name of the set (required for load/save)
func (rcv *SysCfgToolDataSet) SetName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// name of the set (required for load/save)
func SysCfgToolDataSetKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &SysCfgToolDataSet{}
	obj2 := &SysCfgToolDataSet{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf)) - o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf)) - o2)
	return string(obj1.SetName()) < string(obj2.SetName())
}

func (rcv *SysCfgToolDataSet) LookupByKey(key string, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation - 4:])
	start := flatbuffers.UOffsetT(0)
	bKey := []byte(key)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+ 4 * (start + middle))
		obj := &SysCfgToolDataSet{}
		obj.Init(buf, tableOffset)
		comp := bytes.Compare(obj.SetName(), bKey)
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

/// XYZ offsets (must be exactly three values)
func (rcv *SysCfgToolDataSet) OffsetXyz(j int) float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *SysCfgToolDataSet) OffsetXyzLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// XYZ offsets (must be exactly three values)
func (rcv *SysCfgToolDataSet) MutateOffsetXyz(j int, n float64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

/// rotation offsets as Euler angles ZY'Z'' (must be exactly three values)
func (rcv *SysCfgToolDataSet) Orientation(j int) float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *SysCfgToolDataSet) OrientationLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// rotation offsets as Euler angles ZY'Z'' (must be exactly three values)
func (rcv *SysCfgToolDataSet) MutateOrientation(j int, n float64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

/// offsets for radius
func (rcv *SysCfgToolDataSet) ToolRadius() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

/// offsets for radius
func (rcv *SysCfgToolDataSet) MutateToolRadius(n float64) bool {
	return rcv._tab.MutateFloat64Slot(10, n)
}

/// edge orientation value
func (rcv *SysCfgToolDataSet) ToolDataEdgeOri() ToolDataEdgeOri {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return ToolDataEdgeOri(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// edge orientation value
func (rcv *SysCfgToolDataSet) MutateToolDataEdgeOri(n ToolDataEdgeOri) bool {
	return rcv._tab.MutateInt8Slot(12, int8(n))
}

/// Units for XYZ offsets (must be exactly three values)
func (rcv *SysCfgToolDataSet) OffsetXyzunits(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *SysCfgToolDataSet) OffsetXyzunitsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// Units for XYZ offsets (must be exactly three values)
/// Units for rotation offsets (must be exactly three values)
func (rcv *SysCfgToolDataSet) OrientationUnits(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *SysCfgToolDataSet) OrientationUnitsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// Units for rotation offsets (must be exactly three values)
/// Unit for the tool radius
func (rcv *SysCfgToolDataSet) ToolRadiusUnit() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Unit for the tool radius
func SysCfgToolDataSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func SysCfgToolDataSetAddSetName(builder *flatbuffers.Builder, setName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(setName), 0)
}
func SysCfgToolDataSetAddOffsetXyz(builder *flatbuffers.Builder, offsetXyz flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(offsetXyz), 0)
}
func SysCfgToolDataSetStartOffsetXyzVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func SysCfgToolDataSetAddOrientation(builder *flatbuffers.Builder, orientation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(orientation), 0)
}
func SysCfgToolDataSetStartOrientationVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func SysCfgToolDataSetAddToolRadius(builder *flatbuffers.Builder, toolRadius float64) {
	builder.PrependFloat64Slot(3, toolRadius, 0.0)
}
func SysCfgToolDataSetAddToolDataEdgeOri(builder *flatbuffers.Builder, toolDataEdgeOri ToolDataEdgeOri) {
	builder.PrependInt8Slot(4, int8(toolDataEdgeOri), 0)
}
func SysCfgToolDataSetAddOffsetXyzunits(builder *flatbuffers.Builder, offsetXyzunits flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(offsetXyzunits), 0)
}
func SysCfgToolDataSetStartOffsetXyzunitsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SysCfgToolDataSetAddOrientationUnits(builder *flatbuffers.Builder, orientationUnits flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(orientationUnits), 0)
}
func SysCfgToolDataSetStartOrientationUnitsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SysCfgToolDataSetAddToolRadiusUnit(builder *flatbuffers.Builder, toolRadiusUnit flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(toolRadiusUnit), 0)
}
func SysCfgToolDataSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
