// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AppIdmUserInfosT struct {
	Info []*AppIdmUserInfoT
}

func (t *AppIdmUserInfosT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	infoOffset := flatbuffers.UOffsetT(0)
	if t.Info != nil {
		infoLength := len(t.Info)
		infoOffsets := make([]flatbuffers.UOffsetT, infoLength)
		for j := 0; j < infoLength; j++ {
			infoOffsets[j] = t.Info[j].Pack(builder)
		}
		AppIdmUserInfosStartInfoVector(builder, infoLength)
		for j := infoLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(infoOffsets[j])
		}
		infoOffset = builder.EndVector(infoLength)
	}
	AppIdmUserInfosStart(builder)
	AppIdmUserInfosAddInfo(builder, infoOffset)
	return AppIdmUserInfosEnd(builder)
}

func (rcv *AppIdmUserInfos) UnPackTo(t *AppIdmUserInfosT) {
	infoLength := rcv.InfoLength()
	t.Info = make([]*AppIdmUserInfoT, infoLength)
	for j := 0; j < infoLength; j++ {
		x := AppIdmUserInfo{}
		rcv.Info(&x, j)
		t.Info[j] = x.UnPack()
	}
}

func (rcv *AppIdmUserInfos) UnPack() *AppIdmUserInfosT {
	if rcv == nil { return nil }
	t := &AppIdmUserInfosT{}
	rcv.UnPackTo(t)
	return t
}

type AppIdmUserInfos struct {
	_tab flatbuffers.Table
}

func GetRootAsAppIdmUserInfos(buf []byte, offset flatbuffers.UOffsetT) *AppIdmUserInfos {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AppIdmUserInfos{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAppIdmUserInfos(buf []byte, offset flatbuffers.UOffsetT) *AppIdmUserInfos {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AppIdmUserInfos{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AppIdmUserInfos) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AppIdmUserInfos) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AppIdmUserInfos) Info(obj *AppIdmUserInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AppIdmUserInfos) InfoLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AppIdmUserInfosStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AppIdmUserInfosAddInfo(builder *flatbuffers.Builder, info flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(info), 0)
}
func AppIdmUserInfosStartInfoVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AppIdmUserInfosEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
