// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datalayer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ArrayOfFloat64T struct {
	Value []float64
}

func (t *ArrayOfFloat64T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	valueOffset := flatbuffers.UOffsetT(0)
	if t.Value != nil {
		valueLength := len(t.Value)
		ArrayOfFloat64StartValueVector(builder, valueLength)
		for j := valueLength - 1; j >= 0; j-- {
			builder.PrependFloat64(t.Value[j])
		}
		valueOffset = builder.EndVector(valueLength)
	}
	ArrayOfFloat64Start(builder)
	ArrayOfFloat64AddValue(builder, valueOffset)
	return ArrayOfFloat64End(builder)
}

func (rcv *ArrayOfFloat64) UnPackTo(t *ArrayOfFloat64T) {
	valueLength := rcv.ValueLength()
	t.Value = make([]float64, valueLength)
	for j := 0; j < valueLength; j++ {
		t.Value[j] = rcv.Value(j)
	}
}

func (rcv *ArrayOfFloat64) UnPack() *ArrayOfFloat64T {
	if rcv == nil { return nil }
	t := &ArrayOfFloat64T{}
	rcv.UnPackTo(t)
	return t
}

type ArrayOfFloat64 struct {
	_tab flatbuffers.Table
}

func GetRootAsArrayOfFloat64(buf []byte, offset flatbuffers.UOffsetT) *ArrayOfFloat64 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ArrayOfFloat64{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsArrayOfFloat64(buf []byte, offset flatbuffers.UOffsetT) *ArrayOfFloat64 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ArrayOfFloat64{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ArrayOfFloat64) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ArrayOfFloat64) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ArrayOfFloat64) Value(j int) float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *ArrayOfFloat64) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ArrayOfFloat64) MutateValue(j int, n float64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func ArrayOfFloat64Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ArrayOfFloat64AddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func ArrayOfFloat64StartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func ArrayOfFloat64End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
