// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datalayer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ArrayOfUInt32T struct {
	Value []uint32
}

func (t *ArrayOfUInt32T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	valueOffset := flatbuffers.UOffsetT(0)
	if t.Value != nil {
		valueLength := len(t.Value)
		ArrayOfUInt32StartValueVector(builder, valueLength)
		for j := valueLength - 1; j >= 0; j-- {
			builder.PrependUint32(t.Value[j])
		}
		valueOffset = builder.EndVector(valueLength)
	}
	ArrayOfUInt32Start(builder)
	ArrayOfUInt32AddValue(builder, valueOffset)
	return ArrayOfUInt32End(builder)
}

func (rcv *ArrayOfUInt32) UnPackTo(t *ArrayOfUInt32T) {
	valueLength := rcv.ValueLength()
	t.Value = make([]uint32, valueLength)
	for j := 0; j < valueLength; j++ {
		t.Value[j] = rcv.Value(j)
	}
}

func (rcv *ArrayOfUInt32) UnPack() *ArrayOfUInt32T {
	if rcv == nil { return nil }
	t := &ArrayOfUInt32T{}
	rcv.UnPackTo(t)
	return t
}

type ArrayOfUInt32 struct {
	_tab flatbuffers.Table
}

func GetRootAsArrayOfUInt32(buf []byte, offset flatbuffers.UOffsetT) *ArrayOfUInt32 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ArrayOfUInt32{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsArrayOfUInt32(buf []byte, offset flatbuffers.UOffsetT) *ArrayOfUInt32 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ArrayOfUInt32{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ArrayOfUInt32) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ArrayOfUInt32) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ArrayOfUInt32) Value(j int) uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *ArrayOfUInt32) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ArrayOfUInt32) MutateValue(j int, n uint32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func ArrayOfUInt32Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ArrayOfUInt32AddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func ArrayOfUInt32StartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ArrayOfUInt32End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
