// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datalayer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ExtensionT struct {
	Key string
	Value string
}

func (t *ExtensionT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	keyOffset := builder.CreateString(t.Key)
	valueOffset := builder.CreateString(t.Value)
	ExtensionStart(builder)
	ExtensionAddKey(builder, keyOffset)
	ExtensionAddValue(builder, valueOffset)
	return ExtensionEnd(builder)
}

func (rcv *Extension) UnPackTo(t *ExtensionT) {
	t.Key = string(rcv.Key())
	t.Value = string(rcv.Value())
}

func (rcv *Extension) UnPack() *ExtensionT {
	if rcv == nil { return nil }
	t := &ExtensionT{}
	rcv.UnPackTo(t)
	return t
}

type Extension struct {
	_tab flatbuffers.Table
}

func GetRootAsExtension(buf []byte, offset flatbuffers.UOffsetT) *Extension {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Extension{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsExtension(buf []byte, offset flatbuffers.UOffsetT) *Extension {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Extension{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Extension) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Extension) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Extension) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Extension) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ExtensionStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ExtensionAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func ExtensionAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func ExtensionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
