// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datalayer

import (
	"bytes"
	flatbuffers "github.com/google/flatbuffers/go"
)

type LocaleTextT struct {
	Id string `json:"id"`
	Text string `json:"text"`
}

func (t *LocaleTextT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	idOffset := flatbuffers.UOffsetT(0)
	if t.Id != "" {
		idOffset = builder.CreateString(t.Id)
	}
	textOffset := flatbuffers.UOffsetT(0)
	if t.Text != "" {
		textOffset = builder.CreateString(t.Text)
	}
	LocaleTextStart(builder)
	LocaleTextAddId(builder, idOffset)
	LocaleTextAddText(builder, textOffset)
	return LocaleTextEnd(builder)
}

func (rcv *LocaleText) UnPackTo(t *LocaleTextT) {
	t.Id = string(rcv.Id())
	t.Text = string(rcv.Text())
}

func (rcv *LocaleText) UnPack() *LocaleTextT {
	if rcv == nil { return nil }
	t := &LocaleTextT{}
	rcv.UnPackTo(t)
	return t
}

type LocaleText struct {
	_tab flatbuffers.Table
}

func GetRootAsLocaleText(buf []byte, offset flatbuffers.UOffsetT) *LocaleText {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LocaleText{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLocaleText(buf []byte, offset flatbuffers.UOffsetT) *LocaleText {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LocaleText{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *LocaleText) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LocaleText) Table() flatbuffers.Table {
	return rcv._tab
}

/// iso 639.1
func (rcv *LocaleText) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// iso 639.1
func LocaleTextKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &LocaleText{}
	obj2 := &LocaleText{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf)) - o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf)) - o2)
	return string(obj1.Id()) < string(obj2.Id())
}

func (rcv *LocaleText) LookupByKey(key string, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation - 4:])
	start := flatbuffers.UOffsetT(0)
	bKey := []byte(key)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+ 4 * (start + middle))
		obj := &LocaleText{}
		obj.Init(buf, tableOffset)
		comp := bytes.Compare(obj.Id(), bKey)
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

func (rcv *LocaleText) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LocaleTextStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LocaleTextAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func LocaleTextAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(text), 0)
}
func LocaleTextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
