// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datalayer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Watchlists struct {
	_tab flatbuffers.Table
}

func GetRootAsWatchlists(buf []byte, offset flatbuffers.UOffsetT) *Watchlists {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Watchlists{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsWatchlists(buf []byte, offset flatbuffers.UOffsetT) *Watchlists {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Watchlists{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Watchlists) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Watchlists) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Watchlists) Watchlists(obj *Watchlist, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Watchlists) WatchlistsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func WatchlistsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WatchlistsAddWatchlists(builder *flatbuffers.Builder, watchlists flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(watchlists), 0)
}
func WatchlistsStartWatchlistsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func WatchlistsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
