name: Make Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Run check
      run: |
        uname -a
        sudo apt-get update
        sudo apt-get install -y libsystemd-dev libzmq3-dev
        make test
        
      
