name: Make Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run check
      run: |
        uname -a
        ls -lah
        sudo apt-get update
        sudo apt-get install -y libsystemd-dev
        sudo apt install pkg-config
        wget https://github.com/boschrexroth/ctrlx-automation-sdk/releases/download/3.2.0/ctrlx-datalayer-2.7.5.deb
        sudo apt-get install -y -f ./ctrlx-datalayer-2.7.5.deb

    - name: Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Test
      run: |
        go mod download
        go mod vendor
        go mod tidy
        go test -race -short -count=1 -mod=vendor ./test/datalayer ./test/sseclient ./test/token

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22
    - name: Run go test
      run: |
        ls -lah
        go mod download
        go mod vendor
        go test -race -short -count=1 -mod=vendor ./test/datalayer ./test/sseclient ./test/token

