name: Make Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Run check
      run: |
        uname -a
        ls -lah
        sudo apt-get update
        sudo apt-get install -y libsystemd-dev libzmq3-dev
        wget https://github.com/boschrexroth/ctrlx-automation-sdk/releases/download/1.12.0/ctrlx-datalayer.deb
        sudo apt-get install -y -f ./ctrlx-datalayer.deb
    
    - name: Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -race -short -count=1 -mod=vendor ./test/datalayer
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run go test
      run: |
        ls -lah
        go mod download
        go mod vendor
        go test -race -short -count=1 -mod=vendor ./test/datalayer
      
